### PR TITLE
School discovery

### PR DESCRIPTION
**Pull request by psd**
School and address registers for discovery of schools.

### CODE REVIEW

**Comment by psd** [comment]
Updated to make the local-authority registers owned by GDS and turned the min/max ages to be integers.

**Comment by psd** [comment]
Added diocese

**Comment by psd** [comment]
Made a couple of school fields lists: denomination ☞ denominations, and diocese ☞ dioceses

**Comment by psd** [comment]
Can should be able to merge this and load the discovery registers now.

**Comment by robmckinnon** [comment]
Looks good, we'll merge and trial it in discovery.

**Pull request merged**
